version: "3.9"
services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    ports:
      - 65432:5432
    restart: always
    environment:
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=K945Bm9Qqg3JRRt6
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - backend
  app:
    build: .
    container_name: rentx
    links:
      - database_ignite:database
    ports:
      - 3333:3333
    networks:
      - backend
    depends_on:
      - database_ignite
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: "bridge"