version: "3.9"
services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local